"""
Django settings for somnus project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import environ
import os

# Inicializa o environ
env = environ.Env(
    DEBUG=(bool, False)
)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY') 

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'accounts.Usuario'

# Application definition

INSTALLED_APPS = [

    'jazzmin',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_bootstrap5',
    'core',
    'accounts',
    'ethics',
    'adminsortable2',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# if DEBUG:
#     # Add django_browser_reload only in DEBUG mode
#     INSTALLED_APPS += ["django_browser_reload"]

#     # Add django_browser_reload middleware only in DEBUG mode
#     MIDDLEWARE += [
#         "django_browser_reload.middleware.BrowserReloadMiddleware",
#     ]


ROOT_URLCONF = 'somnus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'somnus.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': env('POSTGRES_DB'),
#         'USER': env('POSTGRES_USER'),
#         'PASSWORD': env('POSTGRES_PASSWORD'),
#         'HOST': env('DB_HOST'),
#         'PORT': env('DB_PORT'),
#     }
# }

DATABASES = {
    'default': env.db(),
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

JAZZMIN_SETTINGS = {
    "site_title": "Somnus Admin",
    "site_header": "Somnus",
    "site_brand": "Somnus",
    "site_logo": "images/icone - Somnus.png",
    "login_logo": "images/icone - Somnus.png",
    "site_icon": "images/icone - Somnus.png",
    "welcome_sign": "Bem-vindo ao Gerenciador Somnus",
    "copyright": "Somnus Project",
    "user_avatar": None,

    # Ícones para as Models (FontAwesome 5 Free)
    "icons": {
        "auth": "fas fa-users-cog",
        "accounts.Usuario": "fas fa-user-md",           # Médico/Usuário
        "core.Questionario": "fas fa-poll-h",           # Pesquisa/Questionário
        "core.Secao": "fas fa-th-list",                 # Lista de seções
        "core.Pergunta": "fas fa-question-circle",       # Pergunta
        "core.Alternativa": "fas fa-check-square",      # Opções de escolha
        "core.RespostaQuestionario": "fas fa-clipboard-check", # Respostas completas
        "core.RespostaPergunta": "fas fa-comment-dots", # Respostas individuais
        "core.RegraEquacao": "fas fa-calculator",       # Lógica de cálculo
        "ethics.TCLE": "fas fa-file-contract",          # Termo de Ética
        "ethics.AceiteTCLE": "fas fa-user-shield",      # Aceite do Termo
    },

    # Ordem do menu lateral
    "order_with_respect_to": [
        "accounts", 
        "core.Questionario", 
        "core.Secao", 
        "core.Pergunta", 
        "core.RegraEquacao",
        "core.RespostaQuestionario",
        "ethics"
    ],

    "show_ui_builder": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-white",
    "accent": "accent-success",           # Verde institucional do Somnus
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",    # Azul escuro institucional
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,     # Melhora a visualização de subitens
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "flatly",                    # Tema limpo e profissional (médico)
    "dark_mode_theme": None,
}