# Generated by Django 6.0 on 2026-01-23 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=255)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrigatoria', models.BooleanField(default=True)),
                ('conteudo', models.TextField()),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('tipo', models.CharField(choices=[('MC', 'Múltipla Escolha'), ('TX', 'Texto Livre'), ('MX', 'Mista (Opções + Texto)')], default='MC', max_length=2)),
                ('depende_de_alternativa', models.ForeignKey(blank=True, help_text='Esta pergunta só aparece se esta alternativa for marcada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perguntas_dependentes', to='core.alternativa')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='alternativa',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='core.pergunta'),
        ),
        migrations.CreateModel(
            name='RegraEquacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('logica', models.TextField(help_text='Explicação ou fórmula para o cálculo')),
                ('questionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.questionario')),
            ],
            options={
                'verbose_name': 'Regra de Cálculo',
                'verbose_name_plural': 'Regras de Cálculos',
            },
        ),
        migrations.CreateModel(
            name='RespostaQuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_submissao', models.DateTimeField(auto_now_add=True)),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.questionario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resposta de Questionário',
                'verbose_name_plural': 'Respostas dos Questionários',
            },
        ),
        migrations.CreateModel(
            name='RespostaPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_texto', models.TextField(blank=True, null=True)),
                ('alternativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.alternativa')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pergunta')),
                ('resposta_questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='core.respostaquestionario')),
            ],
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Ex: Escala DASS-21 ou Dados Demográficos', max_length=200)),
                ('instrucao', models.TextField(blank=True, help_text='Instruções específicas para esta parte do questionário')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('layout', models.CharField(choices=[('LISTA', 'Lista Vertical'), ('TABELA', 'Tabela (Matriz)')], default='LISTA', max_length=10)),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoes', to='core.questionario')),
            ],
            options={
                'verbose_name': 'Seção',
                'verbose_name_plural': 'Seções',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='pergunta',
            name='secao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='core.secao'),
        ),
    ]
