# Generated by Django 6.0 on 2025-12-21 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regraequacao',
            options={'verbose_name': 'Regra de Cálculo', 'verbose_name_plural': 'Regras de Cálculos'},
        ),
        migrations.AlterModelOptions(
            name='respostaquestionario',
            options={'verbose_name': 'Resposta de Questionário', 'verbose_name_plural': 'Respostas dos Questionários'},
        ),
    ]
