# Generated by Django 6.0 on 2025-12-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_regraequacao_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pergunta',
            options={'ordering': ['ordem'], 'verbose_name': 'Pergunta', 'verbose_name_plural': 'Perguntas'},
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='ordem',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
