# Generated by Django 6.0 on 2026-01-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_respostaquestionario_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='config_mista',
            field=models.CharField(choices=[('QUALQUER', 'Pelo menos um (Opção OU Texto)'), ('AMBOS', 'Ambos obrigatórios (Opção E Texto)'), ('APENAS_OPCAO', 'Obrigatório selecionar opção'), ('APENAS_TEXTO', 'Obrigatório preencher texto')], default='QUALQUER', help_text='Define a regra de obrigatoriedade para perguntas mistas.', max_length=15),
        ),
    ]
