# Generated by Django 6.0 on 2026-01-26 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pergunta_config_mista'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='depende_de_texto_de',
            field=models.ForeignKey(blank=True, help_text='A pergunta aparecerá se a pergunta selecionada tiver qualquer texto preenchido.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependentes_por_texto', to='core.pergunta'),
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='depende_de_alternativa',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='depende_de_alternativa',
            field=models.ManyToManyField(blank=True, help_text='A pergunta aparecerá se QUALQUER uma destas alternativas for marcada.', related_name='perguntas_dependentes', to='core.alternativa'),
        ),
    ]
