# Generated by Django 6.0 on 2026-01-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pergunta_depende_de_texto_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='mascara',
            field=models.CharField(choices=[('NENHUMA', 'Nenhuma'), ('HORA', 'Hora (00:00)'), ('ALTURA', 'Altura (0,00 m)'), ('PESO', 'Peso (000,0 kg)'), ('DATA', 'Data (00/00/0000)')], default='NENHUMA', max_length=10),
        ),
    ]
