# Generated by Django 5.1.15 on 2026-01-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pergunta_mascara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='mascara',
            field=models.CharField(choices=[('NENHUMA', 'Nenhuma'), ('HORA', 'Hora (00:00)'), ('ALTURA', 'Altura (0,00 m)'), ('PESO', 'Peso (000,0 kg)'), ('DATA', 'Data (00/00/0000)'), ('OUTRO', 'Outro')], default='NENHUMA', max_length=10),
        ),
    ]
