# Generated by Django 5.1.15 on 2026-01-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pergunta_mascara'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='identificador',
            field=models.CharField(blank=True, help_text='Nome da variável para o Excel (ex: sexo__, idade__). Se vazio, usará o ID da pergunta.', max_length=50, null=True),
        ),
    ]
