# Generated by Django 5.1.15 on 2026-03-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_alternativa_id_alter_pergunta_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respostaquestionario',
            old_name='usuario',
            new_name='pesquisadora',
        ),
        migrations.AlterUniqueTogether(
            name='respostaquestionario',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='respostaquestionario',
            name='paciente_nome',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
