# Generated by Django 5.1.15 on 2026-05-03 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_usuario_respostaquestionario_pesquisadora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Escala de Depressão DASS-21', max_length=100)),
                ('strategy_class', models.CharField(choices=[('DYNAMIC', 'Construtor Visual (Somas, Médias e Regras Simples)'), ('PSQI', 'Índice de Qualidade de Sono de Pittsburgh (PSQI)'), ('IMC', 'Índice de Massa Corporal (IMC)')], default='DYNAMIC', help_text="Selecione 'Construtor Visual' para criar regras pelo sistema, ou escolha uma escala clínica complexa já nativa do sistema.", max_length=50)),
                ('config_dinamica', models.JSONField(blank=True, help_text='Armazena a lógica gerada pela interface do Pesquisador (não precisa ser preenchido manualmente).', null=True)),
                ('questionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escala_config', to='core.questionario')),
            ],
            options={
                'verbose_name': 'Configuração de Escala',
                'verbose_name_plural': 'Configurações de Escalas',
            },
        ),
    ]
