# Generated by Django 5.1.15 on 2026-05-04 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_escalaconfig_delete_regraequacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalaconfig',
            name='questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas_config', to='core.questionario'),
        ),
    ]
