# Generated by Django 5.1.15 on 2026-05-09 21:45

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_escalaconfig_questionario_delete_regraequacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostaquestionario',
            name='codigo_paciente',
            field=models.CharField(default=None, editable=False, max_length=12, unique=True, verbose_name='Código do Paciente'),
        ),
        migrations.AlterField(
            model_name='respostapergunta',
            name='resposta_texto',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respostaquestionario',
            name='paciente_nome',
            field=encrypted_model_fields.fields.EncryptedCharField(null=True, verbose_name='Nome do Paciente (protegido)'),
        ),
        migrations.DeleteModel(
            name='RegraEquacao',
        ),
    ]
