# Generated by Django 5.1.15 on 2026-05-09 21:45
# Corrigido para suportar bancos com dados existentes (NotNullViolation fix)

import uuid
import encrypted_model_fields.fields
from django.db import migrations, models


def gerar_codigos_unicos(apps, schema_editor):
    """Popula codigo_paciente para todos os registros existentes com valores únicos."""
    RespostaQuestionario = apps.get_model('core', 'RespostaQuestionario')
    codigos_usados = set()

    for resposta in RespostaQuestionario.objects.filter(codigo_paciente__isnull=True):
        codigo = str(uuid.uuid4()).replace('-', '')[:10].upper()
        while codigo in codigos_usados or RespostaQuestionario.objects.filter(codigo_paciente=codigo).exists():
            codigo = str(uuid.uuid4()).replace('-', '')[:10].upper()
        codigos_usados.add(codigo)
        resposta.codigo_paciente = codigo
        resposta.save(update_fields=['codigo_paciente'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_escalaconfig_questionario_delete_regraequacao'),
    ]

    operations = [
        # Passo 1: Adiciona o campo como nullable para não quebrar registros existentes
        migrations.AddField(
            model_name='respostaquestionario',
            name='codigo_paciente',
            field=models.CharField(
                null=True,
                blank=True,
                editable=False,
                max_length=12,
                verbose_name='Código do Paciente'
            ),
        ),

        # Passo 2: Popula os registros existentes com códigos únicos
        migrations.RunPython(gerar_codigos_unicos, migrations.RunPython.noop),

        # Passo 3: Torna o campo NOT NULL e UNIQUE agora que todos os registros têm valor
        migrations.AlterField(
            model_name='respostaquestionario',
            name='codigo_paciente',
            field=models.CharField(
                default=None,
                editable=False,
                max_length=12,
                unique=True,
                verbose_name='Código do Paciente'
            ),
        ),

        migrations.AlterField(
            model_name='respostapergunta',
            name='resposta_texto',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respostaquestionario',
            name='paciente_nome',
            field=encrypted_model_fields.fields.EncryptedCharField(null=True, verbose_name='Nome do Paciente (protegido)'),
        ),
        migrations.DeleteModel(
            name='RegraEquacao',
        ),
    ]

