# Generated by Django 5.1.15 on 2026-05-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_respostaquestionario_codigo_paciente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalaconfig',
            name='questionario',
        ),
        migrations.AddField(
            model_name='escalaconfig',
            name='questionarios',
            field=models.ManyToManyField(blank=True, related_name='escalas_config', to='core.questionario'),
        ),
        migrations.AlterField(
            model_name='escalaconfig',
            name='strategy_class',
            field=models.CharField(choices=[('DYNAMIC', 'Construtor Visual (Somas, Médias e Regras Simples)'), ('PSQI', 'Índice de Qualidade de Sono de Pittsburgh (PSQI)'), ('IMC', 'Índice de Massa Corporal (IMC)'), ('DASS21', 'Depression, Anxiety and Stress Scale (DASS-21)'), ('K10', 'Escala de Sofrimento Psicológico de Kessler (K10)'), ('SRQ20', 'Self-Reporting Questionnaire (SRQ-20)'), ('ESE', 'Escala de Sonolência de Epworth (ESE)'), ('AUDIT', 'Alcohol Use Disorder Identification Test (AUDIT)'), ('EMSSP', 'Escala Multidimensional de Suporte Social Percebido (EMSSP)')], default='DYNAMIC', help_text="Selecione 'Construtor Visual' para criar regras pelo sistema, ou escolha uma escala clínica complexa já nativa do sistema.", max_length=50),
        ),
    ]
