# Generated by Django 5.1.15 on 2026-05-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_escalaconfig_questionario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Controla se o questionário está visível para coleta. Desativar é um soft-delete: o registro é preservado no banco.'),
        ),
    ]
