# Generated by Django 5.1.15 on 2026-05-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_ativo_to_questionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalaconfig',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Soft-delete: escalas inativas não aparecem na interface e não são processadas em novas avaliações.'),
        ),
    ]
