# Generated by Django 5.1.15 on 2026-07-20 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_ativo_to_escalaconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_json', models.JSONField(help_text='Dict completo retornado pelo EscalaEngine.processar()')),
                ('score_principal', models.FloatField(blank=True, help_text='Score numérico principal (ex: psqi_global, k10_total, ese_total)', null=True)),
                ('classificacao', models.CharField(blank=True, default='', help_text="Classificação textual principal (ex: 'Qualidade Ruim', 'Baixo Risco')", max_length=150)),
                ('calculado_em', models.DateTimeField(auto_now=True)),
                ('escala_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.escalaconfig', verbose_name='Escala Configurada')),
                ('resposta_questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_escalas', to='core.respostaquestionario', verbose_name='Resposta do Questionário')),
            ],
            options={
                'verbose_name': 'Resultado de Escala (Cache)',
                'verbose_name_plural': 'Resultados de Escalas (Cache)',
                'unique_together': {('resposta_questionario', 'escala_config')},
            },
        ),
    ]
