# Generated by Django 6.0 on 2025-12-21 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ethics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aceitetcle',
            options={'verbose_name': 'Aceite de TCLE', 'verbose_name_plural': 'Aceites de TCLE'},
        ),
    ]
