# Generated by Django 6.0 on 2026-01-25 17:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ethics', '0002_alter_aceitetcle_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aceitetcle',
            unique_together={('usuario', 'tcle')},
        ),
    ]
