# Generated by Django 5.1.15 on 2026-02-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethics', '0003_alter_aceitetcle_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aceitetcle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tcle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
