# Generated by Django 5.1.15 on 2026-02-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethics', '0004_alter_aceitetcle_id_alter_tcle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aceitetcle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tcle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
