# Generated by Django 5.1.15 on 2026-03-02 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_usuario_respostaquestionario_pesquisadora_and_more'),
        ('ethics', '0005_alter_aceitetcle_id_alter_tcle_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aceitetcle',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='aceitetcle',
            name='resposta_questionario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aceite', to='core.respostaquestionario'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='aceitetcle',
            name='usuario',
        ),
    ]
