# Generated by Django 5.1.15 on 2026-09-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethics', '0006_alter_aceitetcle_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aceitetcle',
            name='comprovante_entregue_por',
            field=models.CharField(blank=True, choices=[('IMPRESSO', 'Impresso'), ('EMAIL', 'E-mail'), ('ANOTADO', 'Código anotado pelo participante')], default='', max_length=10, verbose_name='Entrega do comprovante'),
        ),
    ]
