# Generated by Django 5.1.15 on 2026-10-02 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethics', '0007_aceitetcle_comprovante_entregue_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevogacaoConsentimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_paciente', models.CharField(max_length=12, verbose_name='Código do participante')),
                ('questionario_titulo', models.CharField(max_length=255, verbose_name='Questionário')),
                ('tcle_versao', models.FloatField(blank=True, null=True, verbose_name='Versão do TCLE aceita')),
                ('data_coleta', models.DateTimeField(verbose_name='Data da coleta')),
                ('data_revogacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da revogação')),
                ('revogado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revogacoes_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Revogação de consentimento',
                'verbose_name_plural': 'Revogações de consentimento',
                'ordering': ['-data_revogacao'],
            },
        ),
    ]
