# Generated by Django 6.0 on 2025-12-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cor_raca',
            field=models.CharField(choices=[('1', 'Branco'), ('2', 'Preta'), ('3', 'Parda'), ('4', 'Amarela'), ('5', 'Indígena')], max_length=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado_civil',
            field=models.CharField(choices=[('1', 'Solteiro(a)'), ('2', 'Casado(a)'), ('3', 'Com companheiro(a)'), ('4', 'Viúvo(a)'), ('5', 'Outro')], max_length=1),
        ),
    ]
