# Generated by Django 6.0 on 2026-01-25 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usuario_email'),
        ('accounts', '0004_auto_20260125_1623'),
    ]

    operations = [
    ]
