# Generated by Django 5.1.15 on 2026-01-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(help_text='Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_ apenas.', max_length=150, verbose_name='Nome de Usuário'),
        ),
    ]
