# Generated by Django 5.1.15 on 2026-03-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_usuario_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cor_raca',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='sexo',
        ),
    ]
